package HashTableChapter;

/**
 * created by Hannah Li on 18/12/3
 * Project name: LeetcodeProject
 * LeetCode NO.: 389
 */
public class FindDifference389 {


    public static void main(String[] args) {
        String s = "abcd";
        String s1 = "abcde";
        System.out.print(findTheDifference(s,s1));
    }


    /**
     * Given two strings s and t which consist of only lowercase letters.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Find the letter that was added in t.
     * Input:
     * s = "abcd"
     * t = "abcde"
     *
     * Output:
     * e
     *
     * Explanation:
     * 'e' is the letter that was added.
     * 用时4ms
     */
    public static char findTheDifference(String s, String t) {

        int len = s.length();
        char c = t.charAt(len);
        for(int i = 0; i<len; i++){
            c ^= s.charAt(i) ^ t.charAt(i);
        }
        return c;
    }

}
